name: Secret scan

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "41 5 * * 1"

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@a7082b69f5bc6167bbe27ebab82bf6707f267bf6 # main
        with:
          extra_args: --results=verified,unknown
